### ISSUE TITLE
Code not running in the vignette about equating

### ISSUE THREAD

**Issue by JulienMouchninoCCI** [dexter-psychometrics/dexter#13]
In the [vignette about equating](https://cran.r-project.org/web/packages/dexter/vignettes/Equating.html), the code can't run because the `ts` object is not defined.

```
prob_pass = tp = rep(0,29)
for (i in seq_along(0:28)){
  prob_pass[i] = sum(ts$ref_test[ts$new_test==i]>=10) / sum(ts$new_test==i)
  tp[i] = sum(ts$ref_test[ts$new_test>=i]>=10) / sum(ts$new_test>=i)
}
plot(0:28, prob_pass, ylab="Proportion passing the reference test", xlab="New test score", ylim=c(0,1), type = "o", col="red",bty='l')
lines(0:28, tp, type="o", lty=2, col="blue")
```

EDIT : Was the code provided just to illustrate the chart, so is it not meant to be run?

**Comment by jessekps** [comment]
This code is meant as an illustration of what the package actually does internally. It is not really meant to be used but nevertheless, all visible code should be complete in and of itself and not depend on objects created behind the scenes. I probably hid a bit more of the code than I should have. I will have a look, tnx for the report.

**Comment by jessekps** [comment]
unhidden creation of data.frame ts
