### ISSUE TITLE
Request for Theoretical p-values Support for Data Matrix in tia_tables Function

### ISSUE THREAD

**Issue by mometRie** [dexter-psychometrics/dexter#14]
Dear Jesse,

In the tia_tables function, it is currently possible to compute theoretical p-values for maximum scores when the data is stored in a database. However, when using a data matrix, this option is not available.

Would it be possible to add support for computing theoretical p-values by allowing users to manually input a matrix with item_id and max_score?

Thank you for your consideration!

**Comment by jessekps** [comment]
Sorry, no. That's something you should use a database for.
