### ISSUE TITLE
How to discard NA in DIF?

### ISSUE THREAD

**Issue by frankbach** [dexter-psychometrics/dexter#4]
get_persons(keht21) %>% 
  glimpse()

Rows: 533
Columns: 3
$ person_id <chr> "Ht21hossna01", "Ht21hossna02", "Ht21hossna03", "Ht21hossna05", "Ht21hossna06", "Ht21hossna07", "Ht21hossna0…
$ gender    <chr> "f", "p", "f", "f", "p", "p", "p", "f", "p", "f", "f", "p", NA, "f", "p", "f", "f", "p", "f", "p", "p", "f",…
$ sva       <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "ja", NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…

How to deal with NA's in the gender column in DIF?
Best
Frank

**Comment by jessekps** [comment]
short answer:

```
dd = DIF(db, person_property="gender", predicate = !is.na(gender))
plot(dd)
```

You can use predicates in every analysis function in dexter, they work similar to R subset or dplyr filter statements. 

If you use a database, I would also recommend using specific missing value codes, rather than NA's.
