### ISSUE TITLE
Not a bug, but a wish...

### ISSUE THREAD

**Issue by frankbach** [dexter-psychometrics/dexter#5]
Is it possible to compile https://www.cito.com/our-expertise/implementation/3dc for Mac?

Best regards
Frank Bach

**Comment by jessekps** [comment]
It should be. But I don't own a mac so I would not be able to do it. What I can most probably do (have to check with my employer) is to put the uncompiled (Python) code on my github and you would either have to compile it yourself or just run it in a python interpreter. This will require a little knowledge of python. If that would help, please let me know.

Please note that if you plan to do a standard setting over a LAN (as is intended) only the main computer needs to be a windows computer for the compiled version to work. The other computers can be Mac's or a mix, as long as they have a browser (chrome is preferred).

**Comment by frankbach** [comment]
Yes, that would help. Maybe I can contribute with a version compiled for Mac, then,

Best regards

Frank
_________________________________________

10 jan. 2022 kl. 10:07 skrev Jesse Koops ***@***.******@***.***>>:



It should be. But I don't own a mac so I would not be able to do it. What I can most probably do (have to check with my employer) is to put the uncompiled (Python) code on my github and you would either have to compile it yourself or just run it in a python interpreter. This will require a little knowledge of python. If that would help, please let me know.

Please note that if you plan to do a standard setting over a LAN (as is intended) only the main computer needs to be a windows computer for the compiled version to work. The other computers can be Mac's or a mix, as long as they have a browser (chrome is preferred).

**Comment by jessekps** [comment]
this turns out not to be feasable, sorry
