### ISSUE TITLE
What is a "mc item" ?

### ISSUE THREAD

**Issue by jmouchnino** [dexter-psychometrics/dexter#7]
In the vignette, it's mentionned "mc items".

![image](https://user-images.githubusercontent.com/103758616/207623061-8cc4e14e-7f9c-4a6a-8597-ad0126c2c1bd.png)

What is a "mc item" ?

**Comment by jessekps** [comment]
it is a multiple choice item format, where you have multiple options and only one is correct. I'll write it out in a future version
